### ISSUE TITLE
Tagging / Categorizing / Searching

### ISSUE THREAD

**Issue by TKone7** [TKone7/lightread#10]
Come up with an idea how the posts can be tagged or assigned to categories. 

# User-defined vs. static categorization
This will be the main decision point. Should the user be forced to use existing categorizations or is he able to self define them? Advantages and disadvantages?

# 1:N vs N:N
Is an article in exactly one category or can be assigned to multiple 'topics'?

# How do users find articles?
Will there be a simple category list to browse through or do we supply a full search?

**Comment by RomanBoegli** [comment]
### User-defined vs. static categorization and 1:N vs N:N
Let's force users to assign an article to one category out of a set of categories that we (admins) have predefined. Nonetheless, authors should still be able to tag their articles by 3 to 5 self-defined keywords. Consequently, this implies: *{tbl_content[n]:[1]tbl_category}* and *{tbl_content[1]:[n]tbl_keyword}*. 
**Small disadvantage**: assigned category and keywords could contradict (weird author anyways)
**Big advantages**: easy to implement and great basis for building a search by category view.

### How do users find articles?
I'd say we stick with your initial suggestion of providing a view where categories are shown in tiles. Once a user clicks on a tile, we show the appropriate articles, ascending sorted by publishing time. 
A full search field should definitely be placed into the header. The given inputs could be passed through a sequence of "search locations". Let's say a user types in «bitcoin» then we first look for articles that share great similarity in their title. Secondly, we check, if the search term corresponds to an category. Thirdly, we look for articles that include the search term most often in their body.
As an enhancement, we could come up with a more sophisticated search algorithm (such as [BM25](https://en.wikipedia.org/wiki/Okapi_BM25) for which even a PHP [implementation](https://github.com/KonstantinosMetallinos/BM25-for-PHP/blob/master/Okapi-BM25.php) exists)

**Comment by TKone7** [comment]
I totally support your category and tag approach. Only I think tbl_content <> tbl_keyword should also be a N:N relation so you can still filter by keyword and find many related articles.

I also agree with the search approach. Category and search-field separately. Also, we should allow filtering by tag and user (by clicking on the respective items via hyperlink).

**Comment by RomanBoegli** [comment]
This issue was split into issue 

- [#25 Full Text Search](https://github.com/TKone7/lightread/issues/25)
- [#26 Article Tagging using Keywords](https://github.com/TKone7/lightread/issues/26)
