### ISSUE TITLE
New database tables

### ISSUE THREAD

**Issue by TKone7** [TKone7/lightread#18]
**tbl_price**
_Description_: Caches current prices for the desired cryptocurrency. This saves API calls.

-- auto-generated definition
create table tbl_price
(
    fld_price_id     serial           not null
        constraint tbl_price_pk
            primary key,
    fld_price_sym1   varchar(20)      not null,
    fld_price_sym2   varchar(20)      not null,
    fld_price_value  double precision not null,
    fld_price_update timestamp
);

alter table tbl_price
    owner to postgres;

**tbl_nodes**
_Description_: Allows the storing of node information to which the application can talk to. In the column fld_active you can store if the node should be used. One can define multiple nodes and we will provide an interface to change them.

-- auto-generated definition
create table tbl_nodes
(
    fld_node_id       serial not null
        constraint tbl_nodes_pk
            primary key,
    fld_node_tls      text,
    fld_node_macaroon text,
    fld_node_ip       varchar(255),
    fld_active        boolean default false
);

alter table tbl_nodes
    owner to postgres;

**Comment by RomanBoegli** [comment]
I included it in the ERD.
