### ISSUE TITLE
tbl_Attachment

### ISSUE THREAD

**Issue by RomanBoegli** [TKone7/lightread#19]
![grafik](https://user-images.githubusercontent.com/22320200/69446234-3e307b00-0d54-11ea-9649-c4d475c5a169.png)

Since we implemented a markdown editor, I suggest to distance ourselves from allowing file uploads. Thus, we could delete **tbl_Attachment**.

Do you consent?

**Comment by TKone7** [comment]
Absolutely, yes. And even in the case, we decide to allow image upload, we could store it in the file system which seems to be the state of the art anyway.
