### ISSUE TITLE
version control on articles

### ISSUE THREAD

**Issue by RomanBoegli** [TKone7/lightread#20]
The discussion arose wether to track the history of an article or not (e.g. WordPress). To accomlish this, we could implement a 1:N relation from **tbl_Content** to itself. The current primary key **fld_cont_id** will then always represent the "parent" or the "ancestor". When a new version of an article gets initialized, the ID of the parent-article will be held in a new field called **fld_cont_parentid**.

 
![grafik](https://user-images.githubusercontent.com/22320200/69447636-32928380-0d57-11ea-8878-9366cdc32201.png)

**Comment by TKone7** [comment]
This approach seems tempting on first sight but holds several pitfalls. First of all, it is necessary to have a published state and a draft state at the same time. I want to store my draft changes but still have the last published state online. This is not doable with this design.
Querying all **current articles** also is not easy.

**Comment by RomanBoegli** [comment]
as discussed on 23. Nov, we no longer pursue this feature
