### ISSUE TITLE
Article Tagging using Keywords

### ISSUE THREAD

**Issue by RomanBoegli** [TKone7/lightread#26]
_recycled from issue #10_

> Let's force users to assign an article to one category out of a set of categories that we (admins) have predefined. Nonetheless, authors should still be able to tag their articles by 3 to 5 self-defined keywords. Consequently, this implies: {tbl_content[n]:[1]tbl_category} and {tbl_content[1]:[n]tbl_keyword}.
> Small disadvantage: assigned category and keywords could contradict (weird author anyways)
> Big advantages: easy to implement and great basis for building a search by category _view.

> I think tbl_content <> tbl_keyword should also be a N:N relation so you can still filter by keyword and find many related articles.

_update:_ Keywords are assigned under the relation {tbl_content[n]:[n]tbl_keyword}

**Comment by TKone7** [comment]
I found this jQuery tool you could use for the autocompletion for tags whilest still allowing to add new custom-made tags: 
https://www.jqueryscript.net/demo/Tagging-System-Autocomplete-Amsify-Suggestags/
![image](https://user-images.githubusercontent.com/34249734/70974555-515f0e00-20a8-11ea-8b5d-56f93df2022b.png)
