### ISSUE TITLE
Category Selector on Article Drafts View

### ISSUE THREAD

**Issue by RomanBoegli** [TKone7/lightread#29]
Each article must be assigned with a category. Hence, the draft view must provide an appropriate control.

**Comment by TKone7** [comment]
Is this duplicate of https://github.com/TKone7/lightread/issues/27? Or what is the difference?

**Comment by RomanBoegli** [comment]
You're right, #27 is redundant. I closed it.

**Comment by TKone7** [comment]
done with 64b802c5dbd46a61ac67117882056e328f4f8962
Be aware of the database changes that need to be applied.
