### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by RomanBoegli** [TKone7/lightread#30]
What should be included:

- architecture (including important concepts such as domain model, router, etc.)
- external services used
- domain model (class diagram / ERD)
- specialities
- design decisions
- short scenario description (what is this application used for)
- implemented use cases (favourable documented in use case diagrams with 1-2 sentences of explanations)

It does not have to be in the same extend as the reference project. AD likes diagrams!
Code documentation would be nice, but it's not expected that all the functions are documented within PHP comments.

**Comment by TKone7** [comment]
I created Github Pages with a simple layout called [Just the Docs](https://github.com/pmarsceill/just-the-docs). From now on we only edit MD files and commit to the repo. It will be automatically updated. 
https://tkone7.github.io/lightread/

**Comment by RomanBoegli** [comment]
![tenor](https://user-images.githubusercontent.com/22320200/70987001-5a0f0e80-20bf-11ea-886b-b319e7a5d15c.gif)
